In [1]:
# Random User documentation site (https://randomuser.me/documentation?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2023-01-01)
# To start using the API you can install the randomuser library running the pip install command.

!pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py): started
  Building wheel for randomuser (setup.py): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5092 sha256=366275a613629df0e76f40aa0e6f03729cb0f4109e15fb7bf3f5b83fdc77e442
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\fc\8d\74\bcdd5e8a9433bfa4c4f9c1cccbfec40139322a28d77f61e45e
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

In [2]:
from randomuser import RandomUser
import pandas as pd

In [3]:
r = RandomUser()

In [18]:
# generate some random user

some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x1fa3c461790>,
 <randomuser.RandomUser at 0x1fa3c461990>,
 <randomuser.RandomUser at 0x1fa3c461750>,
 <randomuser.RandomUser at 0x1fa3c461890>,
 <randomuser.RandomUser at 0x1fa3c4617d0>,
 <randomuser.RandomUser at 0x1fa3c461910>,
 <randomuser.RandomUser at 0x1fa3c461a90>,
 <randomuser.RandomUser at 0x1fa3c4619d0>,
 <randomuser.RandomUser at 0x1fa3c461a10>,
 <randomuser.RandomUser at 0x1fa3c461810>]

In [11]:
# The "Get Methods" functions mentioned at the beginning of this notebook, can generate the required parameters
# to construct a datasete .For example, to get full name, we call get_full_name() function

name = r.get_full_name()
name

'Timian Sviggum'

In [19]:
# Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Peppi Latvala   peppi.latvala@example.com
Violet Turner   violet.turner@example.com
Eemil Ylitalo   eemil.ylitalo@example.com
Mie Rosenlund   mie.rosenlund@example.com
Zoe Holt   zoe.holt@example.com
Rosa Frazier   rosa.frazier@example.com
Babür Akan   babur.akan@example.com
Ryder Brar   ryder.brar@example.com
Kieran Delsing   kieran.delsing@example.com
Marjorie Palmer   marjorie.palmer@example.com

In [20]:
# Generating image of users

for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/women/28.jpg
https://randomuser.me/api/portraits/women/85.jpg
https://randomuser.me/api/portraits/men/56.jpg
https://randomuser.me/api/portraits/women/32.jpg
https://randomuser.me/api/portraits/women/16.jpg
https://randomuser.me/api/portraits/women/25.jpg
https://randomuser.me/api/portraits/men/43.jpg
https://randomuser.me/api/portraits/men/91.jpg
https://randomuser.me/api/portraits/men/66.jpg
https://randomuser.me/api/portraits/women/86.jpg

In [22]:
# Defining various properties of a user using pandas

def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)     

get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Lillian Mcguinness,female,Trim,Kerry,lillian.mcguinness@example.com,1992-12-09T20:29:31.829Z,https://randomuser.me/api/portraits/women/57.jpg
1,Milka da Conceição,female,Uruguaiana,Alagoas,milka.daconceicao@example.com,1975-10-30T19:07:06.562Z,https://randomuser.me/api/portraits/women/15.jpg
2,Hertha Senger,female,Hemer,Bremen,hertha.senger@example.com,1993-11-22T21:11:54.499Z,https://randomuser.me/api/portraits/women/40.jpg
3,Anna Caballero,female,Cuenca,Extremadura,anna.caballero@example.com,1994-03-12T09:18:13.249Z,https://randomuser.me/api/portraits/women/2.jpg
4,Melike Yeşilkaya,female,Amasya,Çorum,melike.yesilkaya@example.com,1961-08-12T18:54:58.559Z,https://randomuser.me/api/portraits/women/4.jpg
5,Alfred Boot,male,Achterveld,Friesland,alfred.boot@example.com,1957-10-09T05:02:20.586Z,https://randomuser.me/api/portraits/men/42.jpg
6,Laura Gonzalez,female,Palma de Mallorca,Canarias,laura.gonzalez@example.com,1948-11-13T11:42:15.856Z,https://randomuser.me/api/portraits/women/38.jpg
7,Zenaide Farias,female,Jundiaí,Rio Grande do Norte,zenaide.farias@example.com,1945-04-03T05:46:35.343Z,https://randomuser.me/api/portraits/women/13.jpg
8,Hanaé Gerard,female,Saint-Pierre,Saône-et-Loire,hanae.gerard@example.com,1971-01-31T02:09:51.364Z,https://randomuser.me/api/portraits/women/6.jpg
9,Helena Bengtsson,female,Mysen,Oppland,helena.bengtsson@example.com,1966-11-04T22:17:28.845Z,https://randomuser.me/api/portraits/women/60.jpg

In [23]:
# A dataframe thats takes in the properties of the users

df1 = pd.DataFrame(get_users())

# FRUITIVE API

In [24]:
import requests
import json

In [25]:
# We will obtain the fruitvice API data using requests.get("url") function. The data is in a json format

data = requests.get("https://fruityvice.com/api/fruit/all")

In [26]:
# We will retrieve results using json.loads() function

results = json.loads(data.text)

In [27]:
# We will convert our json data into pandas data frame

pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Papaya,42,Caricaceae,Caricacea,Carica,"{'calories': 43, 'fat': 0.4, 'sugar': 1.0, 'ca..."
26,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
27,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
28,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
29,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
30,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
31,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
32,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
33,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
34,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
35,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
36,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
37,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
38,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
39,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
40,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
41,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."

In [28]:
# The result is in a nested json format. The 'nutrition' column contains multiple subcolumns,
# so the data needs to be 'flattened' or normalized

df2 = pd.json_normalize(results)
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Papaya,42,Caricaceae,Caricacea,Carica,43,0.40,1.00,11.00,0.00
26,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
27,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
28,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
29,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
30,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
31,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
32,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
33,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
34,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
35,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
36,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
37,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
38,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
39,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
40,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
41,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78

In [32]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

In [44]:
# How many calories are contained in banana

banana_cal = df2.loc[df2["name"] == 'Banana']
banana_cal.iloc[0]['nutritions.calories']

96

# ASSIGNMENT 3

In [45]:
data2 = requests.get("https://cat-fact.herokuapp.com/facts")

In [46]:
results2 = json.loads(data2.text)

In [47]:
# The drop() method is used to drop columns from a DataFrame. 
# The drop() method takes two arguments: the column names to be dropped and an optional inplace argument. 
# The inplace argument specifies whether the changes should be made to the original DataFrame or a copy of the DataFrame. 
# If the inplace argument is set to True, the changes will be made to the original DataFrame.

df3 = pd.DataFrame(results2)
df3.drop(columns="status",inplace=True)
df3

,_id,user,text,__v,source,updatedAt,type,createdAt,deleted,used
0,58e008780aac31001185ed05,58e007480aac31001185ecef,Owning a cat can reduce the risk of stroke and...,0,user,2020-08-23T20:20:01.611Z,cat,2018-03-29T20:20:03.844Z,False,False
1,58e009390aac31001185ed10,58e007480aac31001185ecef,"Most cats are lactose intolerant, and milk can...",0,user,2020-08-23T20:20:01.611Z,cat,2018-03-04T21:20:02.979Z,False,False
2,588e746706ac2b00110e59ff,588e6e8806ac2b00110e59c3,Domestic cats spend about 70 percent of the da...,0,user,2020-08-26T20:20:02.359Z,cat,2018-01-14T21:20:02.750Z,False,True
3,58e008ad0aac31001185ed0c,58e007480aac31001185ecef,The frequency of a domestic cat's purr is the ...,0,user,2020-08-24T20:20:01.867Z,cat,2018-03-15T20:20:03.281Z,False,True
4,58e007cc0aac31001185ecf5,58e007480aac31001185ecef,Cats are the most popular pet in the United St...,0,user,2020-08-23T20:20:01.611Z,cat,2018-03-01T21:20:02.713Z,False,False